apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ohrheld-proxy-ghcr-secret
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: machine-identity
        secretNamespace: infisical
      secretsScope:
        projectSlug: base3
        envSlug: production
        secretsPath: "/github-container-registry"
  managedSecretReference:
    secretName: ghcr-secret
    secretType: kubernetes.io/dockerconfigjson
